name: Deploy to Amazon s3

on:			
  push:			
    branches: [ "githubaction" ]
env:			
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: sihyun-webserver

permissions:		
  contents: read
  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install --force

      - name: Build                   # React Build
        run: CI='' npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1	
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
    
      - name: Upload to AWS S3
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./build s3://${{env.S3_BUCKET_NAME}}
            
      - name: Invalidate CloudFront Cache # 새로 리소스를 업데이트할 때 기존 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E6T7MRWN3K12L --paths "/*"

